export default [
  'Chihuahua',
  'Japanese spaniel',
  'Maltese dog, Maltese terrier, Maltese',
  'Pekinese, Pekingese, Peke',
  'Shih-Tzu',
  'Blenheim spaniel',
  'papillon',
  'toy terrier',
  'Rhodesian ridgeback',
  'Afghan hound, Afghan',
  'basset, basset hound',
  'beagle',
  'bloodhound, sleuthhound',
  'bluetick',
  'black-and-tan coonhound',
  'Walker hound, Walker foxhound',
  'English foxhound',
  'redbone',
  'borzoi, Russian wolfhound',
  'Irish wolfhound',
  'Italian greyhound',
  'whippet',
  'Ibizan hound, Ibizan Podenco',
  'Norwegian elkhound, elkhound',
  'otterhound, otter hound',
  'Saluki, gazelle hound',
  'Scottish deerhound, deerhound',
  'Weimaraner',
  'Staffordshire bullterrier, Staffordshire bull terrier',
  'American Staffordshire terrier, Staffordshire terrier, American pit bull terrier, pit bull terrier',
  'Bedlington terrier',
  'Border terrier',
  'Kerry blue terrier',
  'Irish terrier',
  'Norfolk terrier',
  'Norwich terrier',
  'Yorkshire terrier',
  'wire-haired fox terrier',
  'Lakeland terrier',
  'Sealyham terrier, Sealyham',
  'Airedale, Airedale terrier',
  'cairn, cairn terrier',
  'Australian terrier',
  'Dandie Dinmont, Dandie Dinmont terrier',
  'Boston bull, Boston terrier',
  'miniature schnauzer',
  'giant schnauzer',
  'standard schnauzer',
  'Scotch terrier, Scottish terrier, Scottie',
  'Tibetan terrier, chrysanthemum dog',
  'silky terrier, Sydney silky',
  'soft-coated wheaten terrier',
  'West Highland white terrier',
  'Lhasa, Lhasa apso',
  'flat-coated retriever',
  'curly-coated retriever',
  'golden retriever',
  'Labrador retriever',
  'Chesapeake Bay retriever',
  'German short-haired pointer',
  'vizsla, Hungarian pointer',
  'English setter',
  'Irish setter, red setter',
  'Gordon setter',
  'Brittany spaniel',
  'clumber, clumber spaniel',
  'English springer, English springer spaniel',
  'Welsh springer spaniel',
  'cocker spaniel, English cocker spaniel, cocker',
  'Sussex spaniel',
  'Irish water spaniel',
  'kuvasz',
  'schipperke',
  'groenendael',
  'malinois',
  'briard',
  'kelpie',
  'komondor',
  'Old English sheepdog, bobtail',
  'Shetland sheepdog, Shetland sheep dog, Shetland',
  'collie',
  'Border collie',
  'Bouvier des Flandres, Bouviers des Flandres',
  'Rottweiler',
  'German shepherd, German shepherd dog, German police dog, alsatian',
  'Doberman, Doberman pinscher',
  'miniature pinscher',
  'Greater Swiss Mountain dog',
  'Bernese mountain dog',
  'Appenzeller',
  'EntleBucher',
  'boxer',
  'bull mastiff',
  'Tibetan mastiff',
  'French bulldog',
  'Great Dane',
  'Saint Bernard, St Bernard',
  'Eskimo dog, husky',
  'malamute, malemute, Alaskan malamute',
  'Siberian husky',
  'affenpinscher, monkey pinscher, monkey dog',
  'basenji',
  'pug, pug-dog',
  'Leonberg',
  'Newfoundland, Newfoundland dog',
  'Great Pyrenees',
  'Samoyed, Samoyede',
  'Pomeranian',
  'chow, chow chow',
  'keeshond',
  'Brabancon griffon',
  'Pembroke, Pembroke Welsh corgi',
  'Cardigan, Cardigan Welsh corgi',
  'toy poodle',
  'miniature poodle',
  'standard poodle',
  'Mexican hairless',
  'dingo, warrigal, warragal, Canis dingo',
  'dhole, Cuon alpinus',
  'African hunting dog, hyena dog, Cape hunting dog, Lycaon pictus',
  'Donald Trump'
];